Greeting.create(message: 'Good morning🤗!')
Greeting.create(message: 'Bonjour😊!')
Greeting.create(message: 'Buenos dias😊!')
Greeting.create(message: 'Habari za asubuhi😊!')
Greeting.create(message: 'Günaydın😊!')